---
# tasks file for centraServer
- name: install epel-release
  yum:
    name:
      - epel-release
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present
    update_cache: true
  notify: start_nginx

- name: disable default route
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: DEFROUTE=no
    
- name: enable default route on eth1
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
